name: Sync plugin to S3

on:
   release:
     types: [published]

env:
  REPO_NAME: ${{ github.event.repository.name }}
  REPO_OWNER: ${{ github.event.repository.owner.login }}

permissions:
  contents: write

jobs:
  generate-and-release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Prepare files for upload
      run: |
        mkdir -p _temp_upload_files
        cp -r src _temp_upload_files/
        cp plugin.xml _temp_upload_files

    - name: S3 Sync
      uses: peter-evans/s3-backup@v1
      env:
        ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
        SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
        MIRROR_TARGET: '${{ secrets.S3_BACKET_NAME }}/plugins/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}'
        STORAGE_SERVICE_URL: ${{ secrets.S3_SERVICE_URL }}
        AWS_REGION: ${{ secrets.S3_REGION }}
        MIRROR_SOURCE: './_temp_upload_files'
      with:
        args: --overwrite --remove
